import Sidebar from "./components/bar/Sidebar";
import Join from "./components/bar/Join";
import Header from "./components/Header";
import Head from "next/head";
import Navbar from "./components/bar/Navbar";
import {ArrowLeftIcon} from "@heroicons/react/24/outline";
import Link from "next/link";
import Single from "./components/card/Single";

export default function CardDetail() {
    return (
        <div>
            <Head>
                <title>Next.js Tailwind Css</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header name="card detail"/>

            <main className="pt-16">
                <Link href="/">
                    <ArrowLeftIcon className="fixed text-white top-4 left-4 w-6 h-6 z-10"></ArrowLeftIcon>
                </Link>

                <Sidebar/>

                <section className="container mx-auto sm:px-0 md:px-0 lg:px-64 xl:px-64 2xl:px-64">
                    <Single/>
                </section>

                <Join/>
            </main>

            <Navbar/>
        </div>
    )
}