import Head from 'next/head'
import Navbar from "./components/bar/Navbar";
import Header from "./components/Header";
import Sidebar from "./components/bar/Sidebar";
import Join from "./components/bar/Join";
import Card from "./components/card/Card";
import {FunnelIcon} from "@heroicons/react/24/outline";
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Next.js Tailwind Css</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header name="welcome"/>

            <main className="pt-16">
                <Sidebar/>

                <section className="container mx-auto sm:px-0 md:px-0 lg:px-64 xl:px-64 2xl:px-64">
                    <Link href="">
                        <div className="flex dark:text-white">
                            <FunnelIcon className="w-6 h-6 mx-3"/>
                            <span className="font-light">Sort by date</span>
                        </div>
                    </Link>

                    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2 2xl:grid-cols-3 gap-1 p-5">
                        <Card href="card-detail"/>
                    </div>
                </section>

                <Join/>
            </main>

            <Navbar/>
        </div>
    )
}