import Head from 'next/head'
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import Join from "./components/Join";

export default function Home() {
    return (
        <div className="">
            <Head>
                <title>Next.js Tailwind Css</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header children="welcome"/>

            <main className="pt-16">
                <Sidebar/>

                <section className="container mx-auto float-none sm:px-0 md:px-0 lg:px-64 xl:px-64 2xl:px-64">
                    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-4 xl:grid-cols-4 2xl:grid-cols-5 gap-1 p-5 place-content-start">
                        <div>
                            <a href="#">
                                <img className="rounded-t-lg w-96" src="/image-1.png"/>
                            </a>
                        </div>
                        <div>
                            <a href="#">
                                <img className="rounded-t-lg w-96" src="/image-2.png"/>
                            </a>
                        </div>
                        <div>
                            <a href="#">
                                <img className="rounded-t-lg w-96" src="/image-3.png"/>
                            </a>
                        </div>
                        <div>
                            <a href="#">
                                <img className="rounded-t-lg w-96" src="/image-4.png"/>
                            </a>
                        </div>
                        <div>
                            <a href="#">
                                <img className="rounded-t-lg w-96" src="/image-5.png"/>
                            </a>
                        </div>
                    </div>
                </section>

                <Join/>
            </main>

            <Navbar/>
        </div>
    )
}