import Head from 'next/head'
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import MenuTable from "./components/MenuTable";
import Alert from "./components/Alert";
import Table from "./components/Table";
import {useState} from "react";
import {Bars2Icon} from "@heroicons/react/24/outline";
import Script from "next/script";
import Link from "next/link";

export default function Menu() {
    const [users] = useState(() => [
        {
            name: 'Ahmet Sefa',
            surname: 'Arşiv',
            email: 'ahmetarsivpm@gmail.com',
            age: 21
        },
        {
            name: 'Ali',
            surname: 'Karabay',
            email: 'alikarabay77@gmail.com',
            age: 21
        },
        {
            name: 'Tayfun',
            surname: 'Erbilen',
            email: 'te@gmail.com',
            age: 29
        },
        {
            name: 'Mehmet',
            surname: 'Seven',
            email: 'mseven@gmail.com',
            age: 29
        },
        {
            name: 'Gökhan',
            surname: 'Kandemir',
            email: 'gkandemir@gmail.com',
            age: 35
        },
        {
            name: 'Ahmet',
            surname: 'Tarık G.',
            email: 'atg@gmail.com',
            age: 24
        }
    ])
    return (
        <div>
            <Head>
                <title>Next.js Tailwind Css</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header children="table"/>

            <main className="pt-16">
                <section className="container mx-auto">
                    <Alert type="Info alert!" message="It was modeled on the exam results page, task: table"/>

                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md">
                        <MenuTable examName="Türkçe" dateTime="09:55" isActive="Başarılı"></MenuTable>
                    </div>
                </section>
                <br/>
                <section className="container mx-auto">
                    <Table
                        searchable={true}
                        head={[
                            {name: 'Ad-Soyad', sortable: true},
                            {name: 'E-posta'},
                            {name: 'Yaş', sortable: true},
                            {name: 'İşlemler', width: 200}
                        ]}
                        body={users && users.map((user, key) => ([
                            <div key={`${user.name} ${user.surname}`}>{user.name} {user.surname}</div>,
                            user.email,
                            <div searchableText={`Yaş ${user.age}`}>{user.age}</div>,
                            [
                                <Link href="">
                                    <span className="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800">Görüntüle</span>
                                </Link>,
                                <Link href="">
                                    <span className="text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">Kaldır</span>
                                </Link>
                            ]
                        ]))}
                    />
                </section>
                <Script src="https://unpkg.com/flowbite@1.5.4/dist/flowbite.js"/>
            </main>

            <Navbar/>
        </div>
    )
}