import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "./components/Header";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import MenuTable from "./components/MenuTable";
import Alert from "./components/Alert";
import Table from "./components/Table";
import {useState} from "react";
import {Bars2Icon} from "@heroicons/react/24/outline";

export default function Menu() {
    const [users, setUsers] = useState(() => [
        {
            name: 'Ahmet Sefa',
            surname: 'Arşiv',
            email: 'ahmetarsivpm@gmail.com',
            age: 21
        },
        {
            name: 'Ali',
            surname: 'Karabay',
            email: 'alikarabay77@gmail.com',
            age: 21
        },
        {
            name: 'Tayfun',
            surname: 'Erbilen',
            email: 'te@gmail.com',
            age: 29
        },
        {
            name: 'Mehmet',
            surname: 'Seven',
            email: 'mseven@gmail.com',
            age: 29
        },
        {
            name: 'Gökhan',
            surname: 'Kandemir',
            email: 'gkandemir@gmail.com',
            age: 35
        },
        {
            name: 'Ahmet',
            surname: 'Tarık G.',
            email: 'atg@gmail.com',
            age: 24
        }
    ])
    return (
        <div>
            <Head>
                <title>Next.js Tailwind Css</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header children="table"/>

            <main className={styles.main}>
                <section className="container mx-auto">
                    <Alert type="Info alert!" message="It was modeled on the exam results page, task: table"/>

                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md">
                        <MenuTable examName="Türkçe" dateTime="09:55" isActive="Başarılı"></MenuTable>
                    </div>
                </section>
                <br/>
                <section className="container mx-auto">
                    <Table
                        searchable={true}
                        head={[
                            {name: 'Ad-Soyad', sortable: true},
                            {name: 'E-posta'},
                            {name: 'Yaş', sortable: true},
                            {name: 'İşlemler', width: 200}
                        ]}
                        body={users && users.map((user, key) => ([
                            <div key={`${user.name} ${user.surname}`}>{user.name} {user.surname}</div>,
                            user.email,
                            <div searchableText={`Yaş ${user.age}`}>{user.age}</div>,
                            [
                                <div id="dropdownDots" className="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                                    <ul className="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownMenuIconButton">
                                        <li>
                                            <a href="#" className="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Düzenle</a>
                                            <a href="#" className="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Görüntüle</a>
                                            <a href="#" className="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Sil</a>
                                        </li>
                                    </ul>
                                </div>,
                                <button id="dropdownMenuIconButton" data-dropdown-toggle="dropdownDots" type="button">
                                    <Bars2Icon className="w-6 h-6"/>
                                </button>
                            ]
                        ]))}
                    />
                </section>
                <script src="https://unpkg.com/flowbite@1.5.4/dist/flowbite.js"></script>
            </main>

            <Footer className={styles.footer}/>

            <Navbar/>
        </div>
    )
}