import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
    ArrowLeftIcon,
    ArrowRightOnRectangleIcon,
    BookmarkIcon, CalendarDaysIcon,
    ChatBubbleLeftRightIcon, CheckCircleIcon, ChevronRightIcon, ComputerDesktopIcon,
    DevicePhoneMobileIcon, DocumentCheckIcon,
    EnvelopeOpenIcon, MapPinIcon,
    PencilSquareIcon,
    UserIcon
} from "@heroicons/react/24/outline";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Modal from "./components/Modal";

export default function Profile() {
    return (
        <div>
            <Head>
                <title>Next.js Tailwind Css</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header children="profile"/>

            <main className="pt-16">
                <a href="/">
                    <ArrowLeftIcon className="fixed text-white top-4 left-4 w-6 h-6"></ArrowLeftIcon>
                </a>
                <section className="container mx-auto">
                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md">
                        <div className="border-b dark:border-gray-700 p-5">
                            <div className="bg-white dark:bg-gray-900 shadow-md rounded-lg float-right w-10 h-10 p-2">
                                <PencilSquareIcon className="text-blue w-6 h-6"/>
                            </div>
                            <UserIcon className="text-blue w-12 h-12 mr-2 float-left"/>
                            <span className="text-xl font-medium">Example Name</span>
                        </div>

                        <div className="border-b dark:border-gray-700 p-5">
                            <EnvelopeOpenIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                            <span className="text-gray-500 dark:text-gray-300">user@example.com</span>
                            <CheckCircleIcon className="text-blue w-6 h-6  float-right"/>
                        </div>

                        <div className="p-5">
                            <DevicePhoneMobileIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                            <span className="text-gray-500 dark:text-gray-300">+90 555 555 55 55</span>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md mt-20">
                        <Modal></Modal>
                        <a href="#" data-modal-toggle="defaultModal" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <ChatBubbleLeftRightIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                                <span className="text-gray-500 dark:text-gray-300">Destek</span>
                                <span className="bg-blue text-white rounded-lg text-xs font-medium p-1 ml-10">Yeni</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <MapPinIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                                <span className="text-gray-500 dark:text-gray-300">Adreslerim</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <BookmarkIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                                <span className="text-gray-500 dark:text-gray-300">Derslerim</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <DocumentCheckIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                                <span className="text-gray-500 dark:text-gray-300">Sonuçlarım</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <CalendarDaysIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                                <span className="text-gray-500 dark:text-gray-300">Randevularım</span>
                                <span className="bg-blue text-white rounded-lg text-xs font-medium p-1 ml-10">Yeni</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <ComputerDesktopIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                                <span className="text-gray-500 dark:text-gray-300">Canlı Derslerim</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <ArrowRightOnRectangleIcon className="text-blue w-6 h-6 mr-2 float-left"/>
                                <span className="text-gray-500 dark:text-gray-300">Çıkış Yap</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>
                    </div>


                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md mt-5">
                        <label className="text-gray-500 dark:text-gray-300 text-xs pl-5">Versiyon</label>
                        <a href="#" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <span className="text-gray-500 dark:text-gray-300">2.13.12</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>
                    </div>

                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md mt-20">
                        <label className="text-gray-500 dark:text-gray-300 text-xs pl-5">Language - Dil</label>
                        <a href="#" className="border-b dark:border-gray-700 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:focus:bg-gray-900 w-full h-full p-5">
                            <div>
                                <span className="text-gray-500 dark:text-gray-300">Türkçe</span>
                                <ChevronRightIcon className="text-blue w-6 h-6 float-right"/>
                            </div>
                        </a>
                    </div>
                </section>
            </main>

            <script src="https://unpkg.com/flowbite@1.5.4/dist/flowbite.js"/>

            <Footer className={styles.footer}/>

            <Navbar/>
        </div>
    )
}