import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
    ArrowRightOnRectangleIcon, BellAlertIcon,
    BookmarkIcon, BriefcaseIcon, CalendarDaysIcon,
    ChatBubbleLeftRightIcon, CheckCircleIcon, ChevronRightIcon, ComputerDesktopIcon,
    DevicePhoneMobileIcon, DocumentCheckIcon,
    EnvelopeOpenIcon, HomeIcon, MapPinIcon,
    PencilSquareIcon, SquaresPlusIcon,
    UserIcon
} from "@heroicons/react/24/outline";

export default function Profile() {
    return (
        <div>
            <Head>
                <title>Next.js Tailwind Css</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <header className="bg-purple-800 border-gray-200 px-2 sm:px-4 py-2.5 dark:bg-gray-900 text-center">
                <span className="text-white font-medium text-yellow-400 text-2xl">
                    <a href="#">profile</a>
                </span>
            </header>

            <main className={styles.main}>
                <section className="container mx-auto">
                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md">
                        <div className="border-b dark:border-gray-700 p-5">
                            <div className="bg-white shadow-md rounded-lg w-10 h-10 absolute right-5 md:right-44 p-2">
                                <PencilSquareIcon className="text-purple-800 w-6 h-6"/>
                            </div>
                            <UserIcon className="text-purple-800 w-12 h-12 mr-2 float-left"/>
                            <span className="text-xl font-medium">Example Name</span>
                        </div>

                        <div className="border-b dark:border-gray-700 p-5">
                            <EnvelopeOpenIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                            <span className="text-zinc-500">user@example.com</span>
                            <CheckCircleIcon className="text-purple-800 w-6 h-6  float-right"/>
                        </div>

                        <div className="p-5">
                            <DevicePhoneMobileIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                            <span className="text-zinc-500">+90 555 555 55 55</span>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md mt-20">
                        <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                            <div>
                                <ChatBubbleLeftRightIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                                <span className="text-zinc-500">Destek</span>
                                <span className="bg-yellow-400 text-purple-800 rounded-lg text-xs font-medium p-1 ml-10">Yeni</span>
                                <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                            <div>
                                <MapPinIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                                <span className="text-zinc-500">Adreslerim</span>
                                <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                            <div>
                                <BookmarkIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                                <span className="text-zinc-500">Derslerim</span>
                                <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                            <div>
                                <DocumentCheckIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                                <span className="text-zinc-500">Sonuçlarım</span>
                                <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                            <div>
                                <CalendarDaysIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                                <span className="text-zinc-500">Randevularım</span>
                                <span className="bg-yellow-400 text-purple-800 rounded-lg text-xs font-medium p-1 ml-10">Yeni</span>
                                <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                            <div>
                                <ComputerDesktopIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                                <span className="text-zinc-500">Canlı Derslerim</span>
                                <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                            </div>
                        </a>

                        <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                            <div>
                                <ArrowRightOnRectangleIcon className="text-purple-800 w-6 h-6 mr-2 float-left"/>
                                <span className="text-zinc-500">Çıkış Yap</span>
                                <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                            </div>
                        </a>
                    </div>


                        <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md mt-5">
                            <label className="text-zinc-500 text-xs pl-5">Versiyon</label>
                            <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                                <div>
                                    <span className="text-zinc-500">2.13.12</span>
                                    <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                                </div>
                            </a>
                        </div>

                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md mt-20">
                        <label className="text-zinc-500 text-xs pl-5">Language - Dil</label>
                        <a href="#" className="border-b dark:border-gray-700 hover:bg-slate-50 focus:bg-slate-50 w-full h-full p-5">
                            <div>
                                <span className="text-zinc-500">Türkçe</span>
                                <ChevronRightIcon className="text-purple-800 w-6 h-6 float-right"/>
                            </div>
                        </a>
                    </div>
                </section>
            </main>

            <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                   target="_blank"
                   rel="noopener noreferrer">
                    <span className={styles.logo}><Image src="/vercel.svg" alt="Vercel Logo" width={72}
                                                         height={16}/></span>
                </a>
            </footer>

            <div className="w-full h-screen">
                <section id="bottom-navigation" className="block fixed inset-x-0 bottom-0 z-10 bg-white shadow">
                    <div id="tabs" className="flex justify-between">
                        <a href="#"
                           className="w-full focus:text-purple-800 hover:text-purple-800 justify-center inline-block text-center pt-2 pb-1">
                            <HomeIcon className="inline-block mb-1" width="25" height="25"/>
                            <span className="tab tab-home block text-xs">Home</span>
                        </a>
                        <a href="#"
                           className="w-full focus:text-purple-800 hover:text-purple-800 justify-center inline-block text-center pt-2 pb-1">
                            <BellAlertIcon className="inline-block mb-1" width="25" height="25"/>
                            <span className="tab tab-kategori block text-xs">Notification</span>
                        </a>
                        <a href="#"
                           className="w-full focus:text-purple-800 hover:text-purple-800 justify-center inline-block text-center pt-2 pb-1">
                            <SquaresPlusIcon className="inline-block mb-1" width="25" height="25"/>
                            <span className="tab tab-explore block text-xs">Exam</span>
                        </a>
                        <a href="#"
                           className="w-full focus:text-purple-800 hover:text-purple-800 justify-center inline-block text-center pt-2 pb-1">
                            <BriefcaseIcon className="inline-block mb-1" width="25" height="25"/>
                            <span className="tab tab-whishlist block text-xs">Company</span>
                        </a>
                        <a href="#"
                           className="w-full focus:text-purple-800 hover:text-purple-800 justify-center inline-block text-center pt-2 pb-1">
                            <UserIcon className="inline-block mb-1" width="25" height="25"/>
                            <span className="tab tab-account block text-xs">Account</span>
                        </a>
                    </div>
                </section>
            </div>
        </div>
    )
}