import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
    BellAlertIcon, BriefcaseIcon, ChevronRightIcon,
    HomeIcon, InformationCircleIcon, SquaresPlusIcon,
    UserIcon
} from "@heroicons/react/24/outline";
import Header from "./components/header";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import DataTable from "./components/datatable";
import Alert from "./components/alert";

export default function Table() {
    return (
        <div>
            <Head>
                <title>Next.js Tailwind Css</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header children="table"/>

            <main className={styles.main}>
                <section className="container mx-auto">
                    <Alert type="Info alert!" message="It was modeled on the exam results page, task: table"/>

                    <div className="grid grid-cols-1 gap-1 md:grid-cols-1 md:gap-1 shadow-md">
                        <DataTable dateTime="20 October 2022 09:15" examName="Exam Name" isActive="Passed"/>
                    </div>
                </section>
            </main>

            <Footer className={styles.footer}/>

            <Navbar/>
        </div>
    )
}